In [4]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [6]:
iris_data = datasets.load_iris()
type(iris_data)

sklearn.utils.Bunch

In [10]:
iris_data.data.shape, iris_data.target.shape

((150, 4), (150,))

In [11]:
iris_data.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [20]:
from sklearn.preprocessing import StandardScaler, Normalizer

std_scalar = StandardScaler()
std_scalar.fit(iris_data.data)
std_data = std_scalar.transform(iris_data.data)
print(std_data[:5])

norm = Normalizer()
norm.fit(iris_data.data)
norm_data = norm.transform(iris_data.data)
print(norm_data[:5])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
[[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]]


In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(std_data, iris_data.target, test_size=0.20)

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

train_accuracy = []
test_accuracy = []
for k in range(3, 50, 4):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    train_accuracy.append(accuracy_score(y_train, knn.predict(X_train)))
    test_accuracy.append(accuracy_score(y_test, knn.predict(X_test)))


In [17]:
index=0
for k in range(3, 50, 4):
    print("k:{} train_accuracy:{} test_accuracy:{}".format(k,train_accuracy[index], test_accuracy[index]))
    index += 1

k:3 train_accuracy:0.9416666666666667 test_accuracy:1.0
k:7 train_accuracy:0.9416666666666667 test_accuracy:1.0
k:11 train_accuracy:0.95 test_accuracy:1.0
k:15 train_accuracy:0.95 test_accuracy:1.0
k:19 train_accuracy:0.95 test_accuracy:0.9666666666666667
k:23 train_accuracy:0.95 test_accuracy:1.0
k:27 train_accuracy:0.9416666666666667 test_accuracy:1.0
k:31 train_accuracy:0.9333333333333333 test_accuracy:0.9666666666666667
k:35 train_accuracy:0.9 test_accuracy:0.9333333333333333
k:39 train_accuracy:0.8916666666666667 test_accuracy:0.9
k:43 train_accuracy:0.8916666666666667 test_accuracy:0.9
k:47 train_accuracy:0.8833333333333333 test_accuracy:0.8666666666666667


In [22]:
cv_accuracy_with_actual_data = []
cv_accuracy_with_std = []
cv_accuracy_with_norm = []

for k in range(3, 50, 4):
    knn = KNeighborsClassifier(n_neighbors=k)
    cv_accuracy_with_actual_data.append(np.mean(cross_val_score(knn, iris_data.data, iris_data.target)))
    cv_accuracy_with_std.append(np.mean(cross_val_score(knn, std_data, iris_data.target)))
    cv_accuracy_with_norm.append(np.mean(cross_val_score(knn, norm_data, iris_data.target)))

index = 0
for k in range(3, 50, 4):
    print("k:{} auc:{} std_auc:{} norm_auc:{}".format(k, cv_accuracy_with_std[index], cv_accuracy_without_std[index], cv_accuracy_with_norm[index]))
    index += 1


k:3 auc:0.9533333333333334 std_auc:0.9666666666666668 norm_auc:0.9800000000000001
k:7 auc:0.9533333333333334 std_auc:0.9800000000000001 norm_auc:0.96
k:11 auc:0.9466666666666665 std_auc:0.9800000000000001 norm_auc:0.9666666666666668
k:15 auc:0.9466666666666667 std_auc:0.9666666666666668 norm_auc:0.9733333333333334
k:19 auc:0.9533333333333334 std_auc:0.9666666666666668 norm_auc:0.9800000000000001
k:23 auc:0.9333333333333332 std_auc:0.96 norm_auc:0.9733333333333334
k:27 auc:0.9399999999999998 std_auc:0.9466666666666667 norm_auc:0.9733333333333334
k:31 auc:0.9266666666666665 std_auc:0.9333333333333332 norm_auc:0.9733333333333334
k:35 auc:0.9066666666666666 std_auc:0.9533333333333334 norm_auc:0.9800000000000001
k:39 auc:0.9 std_auc:0.9400000000000001 norm_auc:0.9733333333333334
k:43 auc:0.8733333333333334 std_auc:0.9400000000000001 norm_auc:0.9733333333333334
k:47 auc:0.8666666666666668 std_auc:0.9266666666666667 norm_auc:0.9733333333333334


##### Normalization wo